# For more info on HTTP files go to https://aka.ms/vs/httpfile

@host = https://localhost:5050

#Localhost configuration

@lh_catalog_url = https://localhost:5050
@lh_basket_url = https://localhost:5051
@lh_ordering_url = https://localhost:5053

#Docker Configuration

@d_catalog_url = https://localhost:6060
@d_basket_url = https://localhost:6061
@d_ordering_url = https://localhost:6063



### Create a product

POST {{lh_catalog_url}}/products
Content-Type: application/json

{
  "Name": "Taha El maliani 12",
  "Category": ["c1", "c13"],
  "Description": "Description Product 12",
  "ImageFile": "ImageFile Product 12",
  "Price": 20
}

### get all products

GET {{d_catalog_url}}/products?PageNumber=1&PageSize=10
Content-Type: application/json

### Health

GET {{lh_catalog_url}}/health


### get product by Id

GET {{lh_catalog_url}}/products/019b454b-645e-4574-a5b1-ff45143d18df
Content-Type: application/json

### Get Product by category

GET {{lh_catalog_url}}/products/category/c1
Content-Type: application/json

### Update product by id

PUT {{lh_catalog_url}}/products
Content-Type: application/json

{
  "Id": "019b454b-645e-4574-a5b1-ff45143d18df",
  "Name": "Taha El maliani 20",
  "Category": ["c1", "c4"],
  "Description": "Description Product 20",
  "ImageFile": "ImageFile Product 20",
  "Price":  -1991
}

### Delete product by id

DELETE {{lh_catalog_url}}/products/019b454b-645e-4574-a5b1-ff45143d18df
Content-Type: application/json


### add basket

GET {{lh_basket_url}}/basket/taha
Content-Type: application/json

### Add Item

POST {{lh_basket_url}}/basket
Content-Type: application/json

{
  "Cart": {
    "UserName": "Toto",
    "Items": [
      {
        "Quantity": 2,
        "Color": "Red",
        "Price": 500,
        "ProductId": "6B29FC40-CA47-1067-B31D-00DD010662DA",
        "ProductName": "Toto"
      },
      {
        "Quantity": 3,
        "Color": "Yellow",
        "Price": 110,
        "ProductId": "6B29FC40-CA47-1067-B31D-00DD010662DA",
        "ProductName": "Toto P2"
      }
    ]
  }
}


### Get basket Toto
GET {{lh_basket_url}}/basket/Toto


### Delete a basket

DELETE {{lh_basket_url}}/basket/Toto




